version: "3.8"

services:
  backend:
    build: ./backend
    ports: 
      - 8000:8000
    # command: ./docker-entrypoint.sh
    # volumes:
    #   - taxi:/data
  
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 443:3000

# volumes:
#   taxi:
