# Generated by Django 5.0.1 on 2024-01-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedprice',
            old_name='destination',
            new_name='name',
        ),
        migrations.AddField(
            model_name='fixedprice',
            name='formated_address',
            field=models.CharField(default='', max_length=511),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
