# Generated by Django 5.0 on 2024-01-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_history_luggage_history_passengers_travel_luggage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='confirmed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='present',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
