# Generated by Django 5.0.1 on 2024-01-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_rename_destination_fixedprice_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedprice',
            name='formated_address',
            field=models.CharField(max_length=511),
        ),
    ]
