# Generated by Django 5.0 on 2024-01-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_history_confirmed_alter_travel_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
