# Generated by Django 5.0.1 on 2024-03-13 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_fixedprice_formated_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=12)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_destination', to='taxi.location'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_origin', to='taxi.location'),
        ),
    ]
