# Generated by Django 5.0 on 2024-01-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_pricemile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceday',
            name='finish',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='priceday',
            name='satrt',
            field=models.TimeField(),
        ),
    ]
