# Generated by Django 4.2 on 2024-03-17 20:20

from django.db import migrations
from ..add_data_default import price_day_text, price_mile_text


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_alter_history_destination_alter_history_origin'),
    ]

    operations = [
        migrations.RunSQL(price_mile_text),
        migrations.RunSQL(price_day_text)
    ]
