# Generated by Django 5.0 on 2024-01-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_alter_priceday_finish_alter_priceday_satrt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedprice',
            name='priceday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_price', to='taxi.priceday'),
        ),
        migrations.AlterField(
            model_name='joinedprice',
            name='pricemile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_price', to='taxi.pricemile'),
        ),
    ]
