# Generated by Django 5.0 on 2024-01-22 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_alter_joinedprice_priceday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceday',
            old_name='satrt',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='joinedprice',
            name='priceday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_prices', to='taxi.priceday'),
        ),
        migrations.AlterField(
            model_name='joinedprice',
            name='pricemile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_prices', to='taxi.pricemile'),
        ),
    ]
