# Generated by Django 4.2 on 2024-03-17 20:20

from django.db import migrations
from ..add_data_default import joined_price_text


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_add_price_mile_and_day'),
    ]

    operations = [
        migrations.RunSQL(joined_price_text)
    ]
