# Generated by Django 5.0.4 on 2024-04-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_joined_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='date_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
